name: .NET CI/CD with NUnit

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'   # ??i n?u b?n dùng .NET 6 ho?c 7

      - name: Restore dependencies
        run: dotnet restore

      - name: Build project
        run: dotnet build --configuration Release --no-restore

      - name: Run tests with NUnit
        run: dotnet test --configuration Release --no-build --logger "trx;LogFileName=test_results.trx"

      - name: Upload test results
        uses: actions/upload-artifact@v4
        with:
          name: NUnit-TestResults
          path: '**/TestResults/*.trx'
