name: .NET Framework CI with NUnit

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v2

      - name: Restore NuGet packages
        run: nuget restore PRO231-DuAnTotNghiep.sln

      # 🧱 Build toàn bộ solution (bao gồm DuAnTotNghiep.Test)
      - name: Build solution (include test project)
        run: msbuild PRO231-DuAnTotNghiep.sln /p:Configuration=Release /p:Platform="Any CPU"

      # 🧩 In ra danh sách thư mục build để kiểm tra file .dll thực tế
      - name: Show directory structure for debugging
        run: |
          dir
          dir .\DuAnTotNghiep.Test
          dir .\DuAnTotNghiep.Test\bin
          dir .\DuAnTotNghiep.Test\bin\Release

      # ✅ Cài NUnit Console Runner
      - name: Download NUnit Console Runner
        run: nuget install NUnit.ConsoleRunner -Version 3.16.3 -OutputDirectory testrunner

      # ✅ Chạy test (với đường dẫn tuyệt đối an toàn)
      - name: Run NUnit Tests
        run: |
          ./testrunner/NUnit.ConsoleRunner.3.16.3/tools/nunit3-console.exe "$(Resolve-Path .\DuAnTotNghiep.Test\bin\Release\DuAnTotNghiep.Test.dll)"
