name: CI for PRO231-DuAnTotNghiep (.NET Framework + .NET 8 Tests)

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  # Job 1: Build .NET Framework project
  build-framework:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v2

      - name: Restore NuGet packages
        run: nuget restore PRO231-DuAnTotNghiep.sln

      - name: Build .NET Framework solution
        run: msbuild PRO231-DuAnTotNghiep.sln /p:Configuration=Release /p:Platform="Any CPU"

  # Job 2: Build + Run tests (.NET 8)
  test-dotnet:
    runs-on: windows-latest
    needs: build-framework
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET SDK 8
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restore test project
        run: dotnet restore DuAnTotNghiep.Test/DuAnTotNghiep.Test.csproj

      - name: Build test project
        run: dotnet build DuAnTotNghiep.Test/DuAnTotNghiep.Test.csproj --configuration Release --no-restore

      - name: Run .NET 8 tests
        run: dotnet test DuAnTotNghiep.Test/DuAnTotNghiep.Test.csproj --configuration Release --no-build --logger "trx;LogFileName=test_results.trx"
