name: .NET Framework CI/CD

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
  build:
    runs-on: windows-latest   # 🔹 đổi ubuntu-latest → windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v2

      - name: Restore NuGet packages
        run: nuget restore PRO231-DuAnTotNghiep.sln

      - name: Build solution
        run: msbuild PRO231-DuAnTotNghiep.sln /p:Configuration=Release

      - name: Run NUnit tests
        run: |
          dotnet tool install --global NUnit.ConsoleRunner --version 3.15.0
          nunit3-console.exe .\PRO231-DuAnTotNghiep.Tests\bin\Release\PRO231-DuAnTotNghiep.Tests.dll
