name: CI for PRO231-DuAnTotNghiep (.NET Framework + .NET 8 Tests)

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  # 🧱 Job 1: Build ứng dụng .NET Framework
  build-framework:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v2

      - name: Restore NuGet packages
        run: nuget restore PRO231-DuAnTotNghiep.sln

      - name: Build .NET Framework solution
        run: msbuild PRO231-DuAnTotNghiep.sln /p:Configuration=Release /p:Platform="Any CPU"

  # 🧩 Job 2: Build & Run Tests (.NET 8)
  test-dotnet:
    runs-on: windows-latest
    needs: build-framework

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET SDK 8
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      # ⚙️ Tạo file NuGet.Config giả để tránh restore gói .NET Framework
      - name: Disable legacy packages restore
        run: |
          echo "<?xml version='1.0' encoding='utf-8'?><configuration><disabledPackageSources><add key='local' value='true' /></disabledPackageSources></configuration>" > NuGet.Config

      # ✅ Khôi phục gói cho test project (chỉ .NET 8)
      - name: Restore NuGet packages for test project
        run: dotnet restore DuAnTotNghiep.Test/DuAnTotNghiep.Test.csproj /p:BuildProjectReferences=false

      # 🧱 Build riêng test project (bỏ qua project chính .NET Framework)
      - name: Build test project only
        run: dotnet build DuAnTotNghiep.Test/DuAnTotNghiep.Test.csproj --configuration Release /p:BuildProjectReferences=false

      # 🧪 Chạy test (NUnit cho .NET 8)
      - name: Run tests
        run: dotnet test DuAnTotNghiep.Test/DuAnTotNghiep.Test.csproj --configuration Release --no-build /p:BuildProjectReferences=false --logger "trx;LogFileName=test_results.trx"
