name: .NET Framework CI with NUnit

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Setup MSBuild cho .NET Framework
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      # Setup NuGet
      - name: Setup NuGet
        uses: NuGet/setup-nuget@v2

      # Restore tất cả package (NUnit v.v.)
      - name: Restore NuGet packages
        run: nuget restore PRO231-DuAnTotNghiep.sln

      # 🧱 Build project bằng MSBuild (not dotnet)
      - name: Build solution
        run: msbuild PRO231-DuAnTotNghiep.sln /p:Configuration=Release /p:Platform="Any CPU"

      # ✅ Cài NUnit Console Runner
      - name: Download NUnit Console Runner
        run: nuget install NUnit.ConsoleRunner -Version 3.16.3 -OutputDirectory testrunner

      # ✅ Chạy test project .NET Framework
      - name: Run NUnit Tests
        run: |
          ./testrunner/NUnit.ConsoleRunner.3.16.3/tools/nunit3-console.exe .\DuAnTotNghiep.Test\bin\Release\DuAnTotNghiep.Test.dll
